### ISSUE TITLE
Problem to execute sample test

### ISSUE THREAD

**Issue by andreagrifith** [2gis/Winium.StoreApps.CodedUi#21]
Hi. I think your project is awesome. But I have a problem.
First, I compiled the entire project, after downloaded it from git. Then, I created the exe and run it.
At last, I tried to start test_sample.py, but I found an error. 

> System.NullReferenceException in Winium.StoreApps.Driver\Listener\JwpListener.cs row 152
> in Winium.StoreApps.Driver\Listener\JwpListener.cs row 102
> in Winium.StoreApps.Driver\Program.cs row 30

and python show me this error: 
> Traceback (most recent call last):
>   File "C:/Users/Andrea/Documents/WINIUM/Winium.StoreApps.CodedUi/TestExamples/test_sample.py", line 38, in setUp
>     desired_capabilities=self.desired_capabilities)
>   File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 90, in __init__
>     self.start_session(desired_capabilities, browser_profile)
>   File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 177, in start_session
>     response = self.execute(Command.NEW_SESSION, capabilities)
>   File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 234, in execute
>     response = self.command_executor.execute(driver_command, params)
>   File "C:\Python34\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 401, in execute
>     return self._request(command_info[0], url, body=data)
>   File "C:\Python34\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 469, in _request
>     resp = opener.open(request, timeout=self._timeout)
>   File "C:\Python34\lib\urllib\request.py", line 455, in open
>     response = self._open(req, data)
>   File "C:\Python34\lib\urllib\request.py", line 473, in _open
>     '_open', req)
>   File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
>     result = func(*args)
>   File "C:\Python34\lib\urllib\request.py", line 1202, in http_open
>     return self.do_open(http.client.HTTPConnection, req)
>   File "C:\Python34\lib\urllib\request.py", line 1176, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione>

I followed all the instruction wrote in you project page.
What is the problem?
Thanks.

**Comment by NickAb** [comment]
Could you try running pre-build version https://github.com/2gis/Winium.StoreApps.CodedUi/releases/tag/v0.1.0-beta?

`\JwpListener.cs row 152` is related to parsing incoming http request, it would be very helpful if you could provide exact raw request and response messages that were send by python tests, you can use Fiddler to do so, or something similar.

**Comment by andreagrifith** [comment]
I get the same error also with this version.
I used Fiddler to see request and response.
The request is a corrected JSON:

> {"desiredCapabilities": {"deviceName": "Emulator", "locale": "en-US", "debugCodedUI": false, "app": "..\\..\\Winium.StoreApps.TestApp\\AppPackages\\Winium.StoreApps.TestApp_1.0.0.0_AnyCPU_Debug_Test\\Winium.StoreApps.TestApp_1.0.0.0_AnyCPU_Debug.appx", "deviceIpAddress": "127.0.0.1"}}

but i found a 504 error response:

> POST http://127.0.0.1:9999/session HTTP/1.1
> Accept-Encoding: identity
> Host: 127.0.0.1:9999
> Content-Length: 285
> Connection: close
> User-Agent: Python-urllib/3.4
> Content-Type: application/json;charset=UTF-8
> Accept: application/json
> 
> 
> HTTP/1.1 504 Fiddler - Receive Failure
> Date: Mon, 27 Jun 2016 08:43:14 GMT
> Content-Type: text/html; charset=UTF-8
> Connection: close
> Cache-Control: no-cache, must-revalidate
> Timestamp: 10:43:14.001

I see acceptedRequest.StartingLine is null in JspListenerer.cs at row 98 and has no message body.

**Comment by andreagrifith** [comment]
Hi. If i use Postman and sending POST to http://127.0.0.1:9999/session with JSON of desiredCapabilities, it works. 
And, it work also if I send a GET to http://127.0.0.1:9999/session/AwesomeSession/source to receive the page source.
But, if I try to click on a button with http://127.0.0.1:9999/session/AwesomeSession/element/MagicId/click, I receive an error... Or samething similar.... I receice this JSON:

> {
>   "sessionId": "AwesomeSession",
>   "status": 10,
>   "value": "Stale element reference"
> }

**Comment by NickAb** [comment]
What version of selenium bindings do you use in python? Last time we tested it worked on selenium==2.45.0. This driver should work using python bindings (here is a video https://www.youtube.com/watch?v=DE8UbzcHmak).

What is `MagicId`? You should specify element id that was returned by previous call to find element command. When driver find some element, it will assign a unique id to that element and return it, so that you can access that element to get its text, click on it, etc. Most likely `Stale element reference` is thrown because you use element id that was not registered with system.

**Comment by andreagrifith** [comment]
I use selenium 2.53.5. 
I used "MagicId" because I saw the xml response of http://127.0.0.1:9999/session/AwesomeSession/source. 
How can I call the find element command?

**Comment by andreagrifith** [comment]
Thank you so much. Finally I can run it without problems.

**Comment by NickAb** [comment]
Have you managed to run python sample?

**Comment by andreagrifith** [comment]
Yes. I resolved my problem. It was a problem of latest version of selenium. 
But I have a question. What is the difference between the three project? (Driver, Common and CodedUITest)
CodedUITest is used?

**Comment by NickAb** [comment]
- Driver is the HTTP server that implements JSON wire protocol (WebDriver). This is what you connect to from your tests when creating new session. Driver is responsible for AUT and helper server deployment to emulator or device. Driver forwards any commands, that should be executed on device/emulator to CodedUiTestServer.
- CodedUiTestServer is a test server that runs besides your AUT on device or emulator and executes commands like finding elements, clicking, etc.
- Common is just a shared code that is used by both Driver and CodedUiTestServer

**Comment by andreagrifith** [comment]
Has never been tested on Windows 10 Pro?
I installed Visual Studio 2013 and the SDK. But, if I try to get the page source, i get an empty response, both the emulator and on the device...

**Comment by NickAb** [comment]
Do you mean Windows 10 desktop as a host system or Windows 10 as OS of device or emulator?
I assume first, we have tested this driver and Winium.StoreApps on Windows 10 couple times, but we do not have any continues testing for Windows 10, For running and deploying on Windows 10 we had to enable Developer Mode both on host (desktop) system and on mobile (device or emulator).
