### ISSUE TITLE
findElements method throws exception

### ISSUE THREAD

**Issue by pranavkhare** [2gis/Winium.StoreApps.CodedUi#26]
Sometimes findelements method throws this error

An exception of type 'OpenQA.Selenium.WebDriverException' occurred in WebDriver.Support.dll but was not handled in user code

Additional information: Unexpected error. System.Windows.Automation.ElementNotAvailableException: Element not available ---> System.Runtime.InteropServices.COMException: Operation timed out. (Exception from HRESULT: 0x80131505)

   at UIAutomationClient.IUIAutomationTreeWalker.GetFirstChildElementBuildCache(IUIAutomationElement element, IUIAutomationCacheRequest cacheRequest)

   at System.Windows.Automation.TreeWalker.GetFirstChild(AutomationElement element, CacheRequest request)

   --- End of inner exception stack trace ---

   at System.Windows.Automation.TreeWalker.GetFirstChild(AutomationElement element, CacheRequest request)

   at System.Windows.Automation.TreeWalker.GetFirstChild(AutomationElement element)

   at Winium.StoreApps.CodedUITestProject.WiniumElement.<IterFind>d__13.MoveNext()

   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   at Winium.StoreApps.CodedUITestProject.ElementsRegistry.FindElements(WiniumElement root, By strategy)

   at Winium.StoreApps.CodedUITestProject.CommandExecutors.FindElementsExecutor.DoImpl()

   at Winium.StoreApps.CodedUITestProject.CommandExecutors.CommandExecutorBase.Do()

**Comment by NickAb** [comment]
What type of locator do you use with `findElements`? Are you searching by class or name? Is your visual tree big (how many elements does it have)?

**Comment by pranavkhare** [comment]
I am searching by by id. I am implementing to wait until the next page of the app loads. The code fires the command 'findElements' until the next page loads and it finds the element, after which it fires 'isElementDisplayed' command. This seems to work for shorter waits. For longer waits, after some time it throws 

Additional information: Unexpected error. System.Windows.Automation.ElementNotAvailableException: Element not available ---> System.Runtime.InteropServices.COMException: Operation timed out. (Exception from HRESULT: 0x80131505)

**Comment by NickAb** [comment]
This seems to be related to the fact, that elements becomes unavailable while the command is iterating tree, possible due to being called at same time as the transition occurs. What happens in the app at that moment, do you see app UI transitioning into new state? Are you calling `isElementDisplayed` on all found elements? If you are searching by id, then why do you use `findElements` and not `findElement`?

Meanwhile, as a workaround you can try adding exception being thrown to the list of exceptions ignored by WebDriver Wait. In case of java, see https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/support/ui/FluentWait.html#ignoring-java.lang.Class- for reference
